# Generated by Django 4.2.2 on 2023-07-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_futurproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='futurprodcut/'),
        ),
    ]
