# Generated by Django 4.2.2 on 2023-07-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_imghome_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imghome',
        ),
    ]
